<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Maxam Z80</string>
	<key>scopeName</key>
	<string>source.maxam</string>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>z80</string>
	</array>
	<key>uuid</key>
	<string>3A406674-FF3F-4495-BF50-C159AC0245B9</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;[^;:]*</string>
			<key>name</key>
			<string>comment.inline</string>
		</dict>
		<dict>
			<key>match</key>
			<string>((&amp;|#|0x)[0-9a-fA-F]+)</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>%[01]+</string>
			<key>name</key>
			<string>constant.numeric.binary</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9]+</string>
			<key>name</key>
			<string>constant.numeric.decimal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(let|org|run|read|stop|print|nolist|list|align|macro|mend|repeat|until|rend|if|ifnot|else|endif|ENDC|REPT|ENDR|rmem|DB|defb|DW|defw|DS|defs|INCLUDE|INCBIN|SECTION|EQU)\b</string>
			<key>name</key>
			<string>keyword.other.directive.compiler.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(im|ex|exx|djnz|jp(\s+(c|m|nc|nz|p|pe|po|z))?|jr(\s+(c|nc|nz|z))?|ld|ldi|ldir|ldd|ldh|neg|push|pop|add|adc|sub|sbc|and|or|xor|cp|inc|dec|daa|cpl|rlca|rla|rrca|rra|rlc|rl|rrc|rr|sla|swap|sra|srl|bit|res|set|ccf|scf|nop|halt|stop|di|ei|call(\s+(c|m|nc|nz|p|pe|po|z))?|ret(\s+(C|M|NC|NZ|P|PE|PO|Z))?|reti|rst|otdr|otir|out|outi|in|ind|ini|inir)\b</string>
			<key>name</key>
			<string>keyword.other.mnemonic.z80</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.register.alternate.z80</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(af')(?:\W|$)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(a|b|c|d|e|h|l|r|af|bc|de|hl|sp|ix|iy|hx|ixh|lx|ixl|hy|iyh|ly|iyl)\b</string>
			<key>name</key>
			<string>keyword.other.register.z80</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.symbol.label</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(^|:)\s*(\.[a-z_][a-z0-9_\.\?]+)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(@?[a-z_][a-z0-9_\.\?]+)</string>
			<key>name</key>
			<string>variable.other.symbol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\{|\}</string>
			<key>name</key>
			<string>meta.brace.curly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(|\)</string>
			<key>name</key>
			<string>meta.brace.round</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[|\]</string>
			<key>name</key>
			<string>meta.brace.square</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.single</string>
			<key>match</key>
			<string>'[^']*'</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>match</key>
			<string>"[^"]*"</string>
		</dict>
<!--
		<dict>
			<key>begin</key>
			<string>\b'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'\b</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(x\h{2}|[0-2][0-7]{,2}|3[0-6][0-7]|37[0-7]?|[4-7][0-7]?|.)</string>
					<key>name</key>
					<string>constant.character.escape</string>
				</dict>
			</array>
		</dict>
-->
	</array>
</dict>
</plist>
